"""
models/enums.py
Shared enumerations used across Part A and Part B.
These are stable public contracts — do not change values without versioning.
"""
from enum import Enum


class AgentStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InvestigationStatus(str, Enum):
    NEW = "NEW"
    UNDER_REVIEW = "UNDER_REVIEW"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class Verdict(str, Enum):
    CONFIRMED_ISSUE = "CONFIRMED_ISSUE"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ESCALATE = "ESCALATE"
    NO_ACTION_REQUIRED = "NO_ACTION_REQUIRED"


class ProjectStatus(str, Enum):
    PROPOSED = "PROPOSED"
    SANCTIONED = "SANCTIONED"
    IN_PROGRESS = "IN_PROGRESS"
    DELAYED = "DELAYED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class EventType(str, Enum):
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    SANCTION_CREATED = "SANCTION_CREATED"
    SANCTION_UPDATED = "SANCTION_UPDATED"
    BUDGET_UPDATED = "BUDGET_UPDATED"
    COST_UPDATED = "COST_UPDATED"
    PAYMENT_CREATED = "PAYMENT_CREATED"
    PAYMENT_UPDATED = "PAYMENT_UPDATED"
    PROGRESS_UPDATED = "PROGRESS_UPDATED"
    MILESTONE_UPDATED = "MILESTONE_UPDATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_PROCESSED = "DOCUMENT_PROCESSED"
    ASSET_UPDATED = "ASSET_UPDATED"
    COMPLETION_RECORDED = "COMPLETION_RECORDED"
    CONTRACTOR_UPDATED = "CONTRACTOR_UPDATED"
    AGENCY_UPDATED = "AGENCY_UPDATED"
    POLICY_UPDATED = "POLICY_UPDATED"
    DATA_QUALITY_ISSUE = "DATA_QUALITY_ISSUE"


class DataQualityIssueType(str, Enum):
    MISSING = "MISSING"
    INVALID = "INVALID"
    DUPLICATE = "DUPLICATE"
    STALE = "STALE"
    CONFLICTING = "CONFLICTING"
    INCOMPLETE = "INCOMPLETE"


class DocumentStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    FAILED = "FAILED"
    REQUIRES_OCR = "REQUIRES_OCR"


class DocumentType(str, Enum):
    SANCTION_ORDER = "SANCTION_ORDER"
    WORK_ORDER = "WORK_ORDER"
    MEASUREMENT_BOOK = "MEASUREMENT_BOOK"
    COMPLETION_CERTIFICATE = "COMPLETION_CERTIFICATE"
    UTILIZATION_CERTIFICATE = "UTILIZATION_CERTIFICATE"
    AUDIT_REPORT = "AUDIT_REPORT"
    INSPECTION_REPORT = "INSPECTION_REPORT"
    TENDER_DOCUMENT = "TENDER_DOCUMENT"
    AGREEMENT = "AGREEMENT"
    PHOTO_EVIDENCE = "PHOTO_EVIDENCE"
    INVOICE = "INVOICE"
    PAYMENT_VOUCHER = "PAYMENT_VOUCHER"
    POLICY_DOCUMENT = "POLICY_DOCUMENT"
    OTHER = "OTHER"


class OCREngine(str, Enum):
    PADDLE_OCR = "PADDLE_OCR"
    TESSERACT = "TESSERACT"
    NONE = "NONE"


class PolicyRuleStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    WARNING = "WARNING"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class SourceType(str, Enum):
    CSV = "CSV"
    EXCEL = "EXCEL"
    JSON = "JSON"
    API = "API"
    PDF = "PDF"
    MANUAL = "MANUAL"
    SYSTEM = "SYSTEM"


class MatchMethod(str, Enum):
    EXACT = "EXACT"
    NORMALIZED = "NORMALIZED"
    FUZZY = "FUZZY"
    SEMANTIC = "SEMANTIC"
    MANUAL = "MANUAL"
